version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: sqlite:///var/www/html/var/app.db
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8000'

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - '80:80'
